language: node_js
sudo: false
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
    - libpoppler-cpp-dev
    - libpoppler-dev
    - libpoppler-private-dev
    - libfontconfig1-dev
    - libpng12-dev
    - libjpeg-turbo8-dev
    - libtiff5-dev
    - g++-4.9
env: CXX=g++-4.9
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
  - "5"
  - "4"
